services:

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    cap_add:
      - IPC_LOCK
    mem_limit: ${VT_MEM_LIMIT}
    ports:
      - "8200:8200"
    environment:
      VAULT_LOCAL_CONFIG: |
        {
          "storage": {"file": {"path": "/vault/file"}},
          "listener": [
            {"tcp": { "address": "0.0.0.0:8200", "tls_cert_file": "/vault/certs/vault.crt", "tls_key_file": "/vault/certs/vault.key"}}
          ],
          "default_lease_ttl": "168h",
          "max_lease_ttl": "720h",
          "ui": true
        }
      VAULT_API_ADDR: "https://vault:8200" # <--- 이 줄만 추가    
      TZ: Asia/Seoul
    volumes:
      - ./docker/vault/file:/vault/file
      - ./docker/vault/config:/vault/config
      - ./docker/vault/certs:/vault/certs
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
    command: >
      sh -c "
        cp /vault/certs/vault.crt /etc/ssl/certs/vault.crt 2>/dev/null || true;
        cat /vault/certs/vault.crt >> /etc/ssl/certs/ca-certificates.crt 2>/dev/null || true;
        vault server -config=/vault/config/local.json
      "
    networks:
      - backend

networks:
  backend:
    driver: bridge
