# config/permissions.yml

# === 디렉토리 ===
elk:
  owner: "1000:1000"
  mode: "770"
keycloak:
  owner: "1000:1000"
  mode: "770"
vault:
  owner: "101:101"
  mode: "770"
openldap:
  owner: "102:102"
  mode: "770"
bitwarden-bw-data:
  owner: "1000:1000"
  mode: "770"
bitwarden-certs:
  owner: "0:0"
  mode: "750"

# === 인증서/템플릿 파일(직접 지정) ===
vault-cert:
  path: "docker/vault/certs/vault.crt"
  owner: "0:0"
  mode: "640"
vault-key:
  path: "docker/vault/certs/vault.key"
  owner: "0:0"
  mode: "600"

bitwarden-cert:
  path: "docker/bitwarden/certs/bitwarden.crt"
  owner: "0:0"
  mode: "640"
bitwarden-key:
  path: "docker/bitwarden/certs/bitwarden.key"
  owner: "0:0"
  mode: "600"

elk-logstash-template:
  path: "docker/elk/logstash/pipeline/logstash.conf"
  owner: "1000:1000"
  mode: "660"
