services:
  api:
    user: "1001:1001"
  web:
    user: "1001:1001"
  admin:
    user: "1001:1001"
  identity:
    user: "1001:1001"
  sso:
    user: "1001:1001"
  events:
    user: "1001:1001"
  notifications:
    user: "1001:1001"
  attachments:
    user: "1001:1001"
